### PR TITLE
Allow choice of pod or cluster when deploying

### PR DESCRIPTION
**Pull request by houthuis**
## Description

https://shapeblue.sharepoint.com/:w:/r/Shared%20Documents/Development/Roadmap/FR%20Documents/VM%20Deployment%20Planner/DeploymentPlannerFR.docx?d=w0079dc479ca5446985cbb9226a14a08b&csf=1&e=EsWcnl

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by borisstoyanov** [comment]
Hi Henko, have you created any documentation for this feature ?

**Comment by borisstoyanov** [comment]
Hi Henko, have you created any documentation for this feature ?

**Review by borisstoyanov — COMMENTED** [review]
Hi Henko, have you created any documentation for this feature ?

**Comment by houthuis** [comment]
internal PR

**Comment by houthuis** [comment]
please see PR 25

**Pull request closed without merging**
