### PR TITLE
New network type (L2) - Internal

### PR DESCRIPTION
**Pull request by nvazquez**
**Internal PR for New network type (L2)**

JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10102
Feature Specification: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74680920

### Introduction
This feature allows CloudStack administrators to create layer 2 networks on CloudStack. As these networks are purely layer 2, they don't require IP addresses or Virtual Router, only VLAN is necessary (provided by administrator or assigned by CloudStack). Also, network services should be handled externally, e.g. DNS, DHCP, as they are not provided by L2 networks.
As a consequence, a new Guest Network type is created within CloudStack: L2

### Description
- Network offerings and networks support new guest type: L2.
- L2 Network offering creation allows administrator to select Specify VLAN or let CloudStack assign it dynamically.
- L2 Network creation allows administrator to specify VLAN tag (if network offerings allows it) or simply create network.
- VM deployments on L2 networks:
   - VMs should not IP addresses or any network service
   - No Virtual Router deployed on network
   - If Specify VLAN = true for network offering, network gets implemented using a dynamically assigned VLAN 

### UI changes
A new button is added on Networks tab, available for admins, to allow L2 networks creation

### CODE REVIEW

**Comment by nvazquez** [comment]
Added functional fixes for test cases reported by @borisstoyanov 
Ping for review @DaanHoogland @rhtyd

**Comment by yadvr** [comment]
Thanks @nvazquez looks good, however, I'll continue with my review on the upstream PR.

**Review by borisstoyanov — COMMENTED** [review]
Thanks @rhtyd, 
@nvazquez sorry I made you submit this agains our internal repo as well, having in mind that our repo is a mirror of apache/cloudstack it does not makes any sense to have PRs agains both of them. Once merged in community PR we'll pull it here. I think we can close this and stick with community only.

**Comment by nvazquez** [comment]
Thanks @rhtyd @borisstoyanov. No problem @borisstoyanov, I'll close this one

**Pull request closed without merging**
